<script setup lang="ts">
import { ref, watch } from 'vue'
import { User, Sparkles } from 'lucide-vue-next'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Skeleton } from '@/components/ui/skeleton'
import type { JournalAnalysis } from '@/composables/useJournal';
import { toast } from 'vue-sonner';

const props = defineProps<{ journalId: number, initialAnalysis?: JournalAnalysis }>();
const emit = defineEmits(['save', 'cancel']);

const selectedType = ref(props.initialAnalysis?.title || 'initial-thoughts');
const content = ref(props.initialAnalysis?.content || '');
const supabase = useSupabaseClient();
const isEnhancing = ref(false);

watch(() => props.initialAnalysis, (newVal) => {
  if (newVal) {
    selectedType.value = newVal.type;
    content.value = newVal.content;
  } else {
    selectedType.value = 'initial-thoughts';
    content.value = '';
  }
});

const handleSave = () => {
  console.log('NewPersonalAnalysisCard handleSave called. journalId:', props.journalId);
  if (!content.value.trim()) {
    toast.error('Analysis for dream is required.');
    return;
  }

  emit('save', {
    journal_id: props.journalId,
    type: 'personal',
    title: selectedType.value, // Title will be generated by getAnalysisPrettyTitle
    content: content.value,
  });
};

const handleCancel = () => {
  emit('cancel');
};

const handleEnhance = async () => {
  if (!content.value.trim()) {
    toast.error("Analysis content is empty. Nothing to enhance.");
    return;
  }

  isEnhancing.value = true;
  try {
    const { data, error } = await supabase.functions.invoke('enhance', {
      body: {
        type: "personal_analysis",
        object: {
          type: selectedType.value,
          content: content.value,
        },
      },
    });

    if (error) {
      toast.error(`Enhancement failed: ${error.message}`);
      console.error("Enhancement error:", error);
    } else if (data && data.object) {
      content.value = data.object.content;
      selectedType.value = data.object.type; // Update type as well
      toast.success("Analysis enhanced successfully!");
    } else {
      toast.error("Enhancement failed: Unexpected response.");
    }
  } catch (err) {
    toast.error(`An unexpected error occurred: ${err.message}`);
    console.error("Unexpected enhancement error:", err);
  } finally {
    isEnhancing.value = false;
  }
};
</script>

<template>
  <Card class="bg-transparent text-card-foreground flex flex-col gap-6 rounded-xl shadow-sm border-dashed border-2 border-muted-foreground/30">
    <CardHeader class="space-y-3">
      <div class="flex items-center gap-2">
        <User class="h-4 w-4 text-blue-200" aria-hidden="true" />
        <span class="text-sm font-medium text-blue-200">New Personal Analysis</span>
      </div>
      <div class="flex items-center gap-2">
        <Label for="type">Type:</Label>
        <Select v-model="selectedType" :disabled="isEnhancing">
          <SelectTrigger id="type">
            <SelectValue placeholder="Select a type" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="initial-thoughts">Initial Thought</SelectItem>
            <SelectItem value="meditation">Meditation</SelectItem>
            <SelectItem value="retrospective">Retrospective</SelectItem>
          </SelectContent>
        </Select>
      </div>
      <textarea
        v-if="!isEnhancing"
        v-model="content"
        class="border-input placeholder:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:bg-input/30 flex field-sizing-content w-full rounded-md border bg-card px-3 py-2 text-base shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 md:text-sm min-h-[100px]"
        placeholder="What do you think this dream means?"
      ></textarea>
      <div v-else class="space-y-2">
          <Skeleton class="h-4 w-full" />
          <Skeleton class="h-4 w-full" />
          <Skeleton class="h-4 w-[80%]" />
        </div>
      <div class="flex flex-wrap gap-2">
        <Button variant="ghost" class="border h-8 w-full sm:w-auto" @click="handleSave" :disabled="isEnhancing">Save Analysis</Button>
        <Button variant="ghost" class="border h-8 w-full sm:w-auto" @click="handleEnhance" :disabled="isEnhancing">
          <Sparkles class="w-4 h-4" stroke="url(#sparkle-gradient)" />
          <span class="bg-gradient-to-r from-[#a78bfa] to-[#60a5fa] text-transparent bg-clip-text"> Enhance</span>
        </Button>
        <Button variant="ghost" class="h-8 w-full sm:w-auto" @click="handleCancel">Cancel</Button>
      </div>
    </CardHeader>
  </Card>
</template>
