import { ref } from 'vue';

interface JournalEntry {
  id: number;
  title: string;
  date: string;
  description: string;
  content: string;
}

const entries = ref<JournalEntry[]>([]);
const selectedEntry = ref<JournalEntry | null>(null);

const loadEntries = () => {
  // In a real app, this would fetch from an API
  if (entries.value.length === 0) {
    entries.value = [
        { id: 1, title: 'My First Dream', date: '2025-07-31', description: 'A breathtaking flight over a city of crystal.', content: "The transition was seamless, a gentle slide from the fuzzy edges of sleep into a world more real than waking. There was no jarring entry, just a sudden, profound awareness. I was soaring. The air against my skin was cool and carried the faint, clean scent of ozone and something else, something like petrichor after a summer storm. Below me lay a city that defied all laws of architecture and physics, a sprawling metropolis sculpted from pure, incandescent crystal. It wasn't the cold, sharp crystal of ice, but something warm and alive, humming with an internal luminescence. Towers that looked like frozen waterfalls of light spiraled towards a sky of deep indigo, their peaks catching the ethereal glow of a nebula that swirled where the sun should have been. Rainbows weren't just fleeting arcs; they were permanent fixtures, solid bridges of color connecting one spire to another. I banked left, the motion as natural as breathing, and dove into a canyon of shimmering amethyst and rose quartz. The city was utterly silent, yet it vibrated with a palpable energy, a symphony of light and form that resonated deep within my soul. I flew for what felt like an eternity, my reflection a fleeting ghost across the mirrored facades of buildings shaped like blooming flowers and impossible geometric patterns. There was no sense of self, no worry, no memory of the world I'd left behind. There was only the flight, the city, and a feeling of absolute, untethered freedom. It was a baptism in beauty, a profound sense of coming home to a place I had never known. As the dream began to fray at the edges, the vibrant colors softening to grey, the feeling of peace remained, a warm ember I carried back with me into the waking world." },
        { id: 2, title: 'Lucid Adventure', date: '2025-07-30', description: 'Realizing I was dreaming and flying to the moon.', content: "The dream started with a tedious familiarity: I was in my old high school, late for an exam I hadn't studied for. The usual anxiety was a heavy cloak. I was running down a hallway that stretched to an impossible length, the lockers a blur of faded red. Then, I saw the clock on the wall. It was a standard, institutional clock, but its second hand was sweeping backwards, and the numbers were rearranging themselves. The anxiety vanished, replaced by a jolt of pure, electric clarity. The fuzzy logic of the dream world shattered, and the scene snapped into hyper-realistic focus. 'This is a dream,' I thought, and the realization was a key turning in a lock. The hallway shimmered, and I felt a surge of power. I remembered reading about dream stabilization, so I focused on my hands, rubbing them together. The sensation was incredibly real, the friction, the texture of my skin. The dream solidified around me. My first thought was escape. My second was to fly. I pushed the thought of the exam from my mind and focused on the ceiling. I started with a small hop, as the books suggested, and floated for a second before landing. It felt like being on a trampoline in slow motion. 'More intent,' I told myself. I crouched and leaped, pouring all my will into the act of rising. For a moment I just hung there, suspended, and then, with a mental 'push,' I was ascending. I burst through the ceiling into a night sky ablaze with more stars than I had ever seen. The moon was a colossal, luminous pearl, beckoning to me. I flew towards it, the school shrinking below into a tiny model. The silence of space wasn't empty; it was full, a resonant hum that vibrated through me. As I approached the moon, I saw it wasn't the dead rock of reality. Its craters glowed with a soft, internal light, and great, slow-moving rivers of what looked like liquid silver carved paths across its surface. I landed with a gentle bounce on the soft, cool, phosphorescent dust, leaving the first footprint on this impossible world. I looked back at the tiny, blue marble of Earth, feeling like a god, the architect of my own universe." },
        { id: 3, title: 'Strange Encounter', date: '2025-07-29', description: 'A conversation with a well-dressed squirrel.', content: "The forest was bathed in a perpetual golden hour. The leaves on the ancient trees were not green but were spun from delicate threads of gold, casting a warm, dappled light onto the mossy ground. The air was thick with the scent of damp earth and honey. I was following a path made of smooth, grey river stones when I first saw him. He was perched on the low-hanging branch of an oak, meticulously cleaning a monocle with a tiny leaf. He was a red squirrel, but his bearing was that of a seasoned academic. He wore a perfectly tailored tweed waistcoat and a miniature top hat that sat jauntily between his ears. He popped the monocle over his right eye, cleared his throat with a surprisingly resonant 'ahem,' and spoke in a crisp, eloquent voice that seemed far too large for his small body. 'An unexpected visitor, but not an unwelcome one,' he chirped, his tail twitching with amusement. 'It is not often we get dreamers of your... caliber.' I was utterly speechless. He hopped down from the branch, landing silently on the path before me. From a small pocket in his waistcoat, he produced an acorn. But this was no ordinary acorn; it pulsed with a soft, internal light, warm and inviting. 'A token,' he explained, holding it out to me in his tiny paws. 'For those who find their way to the heart of the wood. It holds a single wish.' My mind, suddenly sharp and lucid, reeled with the possibilities. I could wish for anything. But as I stood there in that impossible, beautiful forest, conversing with a creature of pure imagination, I knew what I wanted most. I wanted this. I wanted the key to this world, the ability to return, to explore, to create. 'I wish,' I said, my voice barely a whisper, 'for the power to dream like this, consciously, whenever I choose.' The squirrel's whiskers twitched in what I took to be a smile. 'A most astute choice. The wish of a true explorer, not a mere tourist.' He nodded, and the acorn in my hand dissolved into a cascade of warm, golden light that flowed up my arm and into my chest. It felt like drinking sunshine. A profound sense of control and understanding settled over me. The forest seemed to brighten, the colors becoming even more vibrant, as if responding to my own awareness. The squirrel tipped his hat. 'The worlds within are now yours to map. Do try not to get lost.' And with a final, jauntier twitch of his tail, he scurried up the great oak and vanished among the golden leaves, leaving me alone with my newfound power." },
        { id: 4, title: 'The Submerged Library', date: '2025-07-28', description: 'Exploring a vast library at the bottom of the ocean.', content: "The descent was silent and dark, a gentle drift into the abyssal depths. There was no crushing pressure, no need to breathe. I was a disembodied consciousness, drawn by a faint, pulsing light far below. As I neared, the light resolved into the soft glow of lanterns illuminating the entrance to a colossal structure. It was a library, its architecture a blend of Greco-Roman grandeur and something ancient, almost alien. It was carved from a single, massive piece of obsidian, yet it was not dark. The light came from within, from the books themselves. I swam through the grand entrance, the water parting before me. Inside, the library was a labyrinth of towering shelves that stretched up into the gloom, far beyond the reach of the lantern light. The books were bound not in leather, but in materials that shimmered and shifted—some like mother-of-pearl, others like woven seaweed, and some that seemed to be made of solidified light. I reached out and took one from a shelf. Its title was written in a language I had never seen, yet I understood it perfectly. It was a history of a star that had died a billion years before Earth was born. I opened it, and instead of pages, it contained a miniature, swirling galaxy. I spent what felt like centuries in that silent, submerged world, reading the stories of forgotten gods, the blueprints of impossible machines, and the love poems of creatures made of sound and light. It was a repository of all knowledge, all stories, all possibilities. The silence was not empty; it was filled with the whispers of a million million tales, a chorus of the universe's infinite imagination. I was a student in the ultimate school, a visitor in the most sacred of archives. The knowledge I gained was not factual, but intuitive, a deep, resonant understanding of the interconnectedness of all things." },
        { id: 5, title: 'The Clockwork Forest', date: '2025-07-27', description: 'A forest where all the flora and fauna are automatons.', content: "The forest floor was a complex filigree of brass and copper, and the trees were not made of wood, but of intricate, interlocking gears and cogs. Their leaves were thin sheets of hammered bronze that chimed softly in a breeze that smelled of machine oil and rust. This was a world built by a master craftsman. Every living thing was a mechanical marvel. I watched a deer, its body a beautiful sculpture of polished chrome and steel, gracefully pick its way through the undergrowth, its movements accompanied by a soft, rhythmic ticking. A bird made of spun silver and sapphire flew overhead, its wings beating with a precise, clockwork motion, its song a series of perfectly pitched metallic notes. I knelt to examine a flower, its petals of ruby-red glass unfolding and closing in a slow, deliberate ballet, powered by a tiny, intricate mechanism at its heart. There was no chaos here, no untamed wilderness. Everything was in its right place, moving according to a grand, unseen design. I felt a sense of profound awe at the artistry and ingenuity of it all. I followed a path of interlocking gears deeper into the forest, the rhythmic ticking and whirring of a million tiny machines a soothing, hypnotic symphony. In a clearing, I found the heart of the forest: a colossal, beating heart of brass and crystal, its rhythmic pulses sending waves of energy through the metallic ground, powering this entire clockwork ecosystem. It was a testament to the beauty of order, the elegance of precision. It was a world where nature and machine were not in conflict, but were one and the same, a perfect, harmonious system of breathtaking complexity and grace." },
        { id: 6, title: 'The City of Shifting Streets', date: '2025-07-26', description: 'Navigating a city whose layout changed with every blink.', content: "I found myself standing on a street corner in a city that felt like a fever dream of Victorian London. The architecture was a chaotic jumble of gothic spires, art deco facades, and brutalist concrete, all shrouded in a thick, persistent fog. The air was filled with the scent of coal smoke and rain. I took a step, and the city rearranged itself. The street I was on twisted into a pretzel, the buildings on either side melting and reforming into new, impossible shapes. I blinked, and the grand cathedral in front of me was replaced by a grimy, neon-lit noodle bar. This was a city in a constant state of flux, a labyrinth that reconfigured itself with every passing moment. Getting anywhere was a challenge, a test of intuition and luck. I learned to navigate not by sight, but by feeling, by sensing the subtle currents of change in the urban landscape. I would aim for a destination—a distant clock tower, a glowing sign—and then close my eyes and walk, trusting that the city would guide me. Sometimes I would end up exactly where I wanted to go. Other times, I would find myself in a completely new and unexpected part of the city—a bustling market where vendors sold bottled dreams and memories, a silent, snow-covered park where the statues were of forgotten gods, a library where the books had no words, only colors. It was a disorienting, exhilarating experience. The city was a living, breathing entity, a puzzle that could never be solved. It was a metaphor for the chaotic, unpredictable nature of life itself, a beautiful, terrifying, and endlessly fascinating place to be lost in." },
        { id: 7, title: 'The Symphony of Taste', date: '2025-07-25', description: 'A feast where every flavor was a musical note.', content: "I was a guest at a grand banquet in a hall that seemed to be made of pure, white marble. The long table was laden with dishes that defied description, foods of impossible colors and shapes. There was no sound in the hall, no music, no conversation. The host, a tall, elegant figure with eyes that shimmered like opals, simply smiled and gestured for me to eat. I took a bite of a fruit that looked like a star, its skin the color of a twilight sky. As my teeth broke the skin, a single, perfect note of a cello filled the silence, rich and resonant. The flavor was a complex harmony of sweet and tart, a melody that danced on my tongue. I tried another dish, a spoonful of shimmering, silver soup. This time, a cascade of harp notes, light and ethereal, washed over me. The flavor was delicate and savory, a gentle, flowing river of taste. Each dish was a different instrument, a different part of the orchestra. A spicy, crackling pastry was a burst of trumpets. A cool, smooth jelly was the gentle murmur of a flute. I was not just eating; I was composing a symphony. I began to combine the flavors, creating my own chords and harmonies. The sweet star-fruit and the savory soup created a beautiful, complex chord, a perfect blend of strings and woodwinds. It was a synesthetic experience of the highest order, a blurring of the senses that was both disorienting and profoundly beautiful. I was not just a diner; I was a conductor, a composer, a musician. The meal was a masterpiece, a symphony of taste that I would never forget, a testament to the infinite, creative possibilities of the dreaming mind." }
    ];
  }
};

const selectEntry = (entry: JournalEntry | null) => {
  selectedEntry.value = entry;
};

const findEntryById = (id: number) => {
    return entries.value.find(e => e.id === id) || null;
}

const createEntry = (newEntry: Omit<JournalEntry, 'id' | 'date'>) => {
    const newId = entries.value.length > 0 ? Math.max(...entries.value.map(e => e.id)) + 1 : 1;
    const today = new Date().toISOString().slice(0, 10);
    const entry = { ...newEntry, id: newId, date: today };
    entries.value.push(entry);
    return entry;
}

const updateEntry = (updatedEntry: JournalEntry) => {
    const index = entries.value.findIndex(e => e.id === updatedEntry.id);
    if (index !== -1) {
        entries.value[index] = updatedEntry;
    }
}

const clearSelectedEntry = () => {
    selectedEntry.value = null;
}

export const useJournal = () => {
  return {
    entries,
    selectedEntry,
    loadEntries,
    selectEntry,
    findEntryById,
    createEntry,
    updateEntry,
    clearSelectedEntry
  };
};